#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using InvDataAccess;

namespace InvDataAccess	
{
	public partial class Cliente
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _cliente1;
		public virtual string Cliente1
		{
			get
			{
				return this._cliente1;
			}
			set
			{
				this._cliente1 = value;
			}
		}
		
		private string _nit;
		public virtual string Nit
		{
			get
			{
				return this._nit;
			}
			set
			{
				this._nit = value;
			}
		}
		
		private string _nrc;
		public virtual string Nrc
		{
			get
			{
				return this._nrc;
			}
			set
			{
				this._nrc = value;
			}
		}
		
		private int _empresa;
		public virtual int Empresa
		{
			get
			{
				return this._empresa;
			}
			set
			{
				this._empresa = value;
			}
		}
		
		private IList<Venta> _ventas = new List<Venta>();
		public virtual IList<Venta> Ventas
		{
			get
			{
				return this._ventas;
			}
		}
		
		private IList<Cotizacione> _cotizaciones = new List<Cotizacione>();
		public virtual IList<Cotizacione> Cotizaciones
		{
			get
			{
				return this._cotizaciones;
			}
		}
		
		private IList<Clientestelefono> _clientestelefonos = new List<Clientestelefono>();
		public virtual IList<Clientestelefono> Clientestelefonos
		{
			get
			{
				return this._clientestelefonos;
			}
		}
		
		private IList<Clientesdireccione> _clientesdirecciones = new List<Clientesdireccione>();
		public virtual IList<Clientesdireccione> Clientesdirecciones
		{
			get
			{
				return this._clientesdirecciones;
			}
		}
		
	}
}
#pragma warning restore 1591
