#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using InvDataAccess;

namespace InvDataAccess	
{
	public partial class Compra
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private DateTime _fecha;
		public virtual DateTime Fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				this._fecha = value;
			}
		}
		
		private string _nDoc;
		public virtual string NDoc
		{
			get
			{
				return this._nDoc;
			}
			set
			{
				this._nDoc = value;
			}
		}
		
		private int _proveedores_Id;
		public virtual int Proveedores_Id
		{
			get
			{
				return this._proveedores_Id;
			}
			set
			{
				this._proveedores_Id = value;
			}
		}
		
		private int _pagado;
		public virtual int Pagado
		{
			get
			{
				return this._pagado;
			}
			set
			{
				this._pagado = value;
			}
		}
		
		private Proveedore _proveedore;
		public virtual Proveedore Proveedore
		{
			get
			{
				return this._proveedore;
			}
			set
			{
				this._proveedore = value;
			}
		}
		
		private IList<Comprasdetalle> _comprasdetalles = new List<Comprasdetalle>();
		public virtual IList<Comprasdetalle> Comprasdetalles
		{
			get
			{
				return this._comprasdetalles;
			}
		}
		
	}
}
#pragma warning restore 1591
