#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using InvDataAccess;

namespace InvDataAccess	
{
	public partial class Costo
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private DateTime _fecha;
		public virtual DateTime Fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				this._fecha = value;
			}
		}
		
		private int _ventasDetalles_Id;
		public virtual int VentasDetalles_Id
		{
			get
			{
				return this._ventasDetalles_Id;
			}
			set
			{
				this._ventasDetalles_Id = value;
			}
		}
		
		private int _comprasDetalles_Id;
		public virtual int ComprasDetalles_Id
		{
			get
			{
				return this._comprasDetalles_Id;
			}
			set
			{
				this._comprasDetalles_Id = value;
			}
		}
		
		private Comprasdetalle _comprasdetalle;
		public virtual Comprasdetalle Comprasdetalle
		{
			get
			{
				return this._comprasdetalle;
			}
			set
			{
				this._comprasdetalle = value;
			}
		}
		
		private Ventasdetalle _ventasdetalle;
		public virtual Ventasdetalle Ventasdetalle
		{
			get
			{
				return this._ventasdetalle;
			}
			set
			{
				this._ventasdetalle = value;
			}
		}
		
	}
}
#pragma warning restore 1591
