#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using InvDataAccess;

namespace InvDataAccess	
{
	public partial class Cotizacione
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _codigo;
		public virtual string Codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				this._codigo = value;
			}
		}
		
		private DateTime _fecha;
		public virtual DateTime Fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				this._fecha = value;
			}
		}
		
		private int _clientes_Id;
		public virtual int Clientes_Id
		{
			get
			{
				return this._clientes_Id;
			}
			set
			{
				this._clientes_Id = value;
			}
		}
		
		private Cliente _cliente;
		public virtual Cliente Cliente
		{
			get
			{
				return this._cliente;
			}
			set
			{
				this._cliente = value;
			}
		}
		
		private IList<Cotizacionesdetalle> _cotizacionesdetalles = new List<Cotizacionesdetalle>();
		public virtual IList<Cotizacionesdetalle> Cotizacionesdetalles
		{
			get
			{
				return this._cotizacionesdetalles;
			}
		}
		
	}
}
#pragma warning restore 1591
