#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using InvDataAccess;

namespace InvDataAccess	
{
	public partial class InvEntitiesModel : OpenAccessContext, IInvEntitiesModelUnitOfWork
	{
		private static string connectionStringName = @"InvdbConnection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("EntitiesModel.rlinq");
		
		public InvEntitiesModel()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public InvEntitiesModel(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public InvEntitiesModel(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public InvEntitiesModel(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public InvEntitiesModel(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<Ventasdetalle> Ventasdetalles 
		{
			get
			{
				return this.GetAll<Ventasdetalle>();
			}
		}
		
		public IQueryable<Venta> Ventas 
		{
			get
			{
				return this.GetAll<Venta>();
			}
		}
		
		public IQueryable<Usuario> Usuarios 
		{
			get
			{
				return this.GetAll<Usuario>();
			}
		}
		
		public IQueryable<Tipodocumento> Tipodocumentos 
		{
			get
			{
				return this.GetAll<Tipodocumento>();
			}
		}
		
		public IQueryable<Proveedoresdireccione> Proveedoresdirecciones 
		{
			get
			{
				return this.GetAll<Proveedoresdireccione>();
			}
		}
		
		public IQueryable<Proveedorescontacto> Proveedorescontactos 
		{
			get
			{
				return this.GetAll<Proveedorescontacto>();
			}
		}
		
		public IQueryable<Proveedore> Proveedores 
		{
			get
			{
				return this.GetAll<Proveedore>();
			}
		}
		
		public IQueryable<Producto> Productos 
		{
			get
			{
				return this.GetAll<Producto>();
			}
		}
		
		public IQueryable<Marca> Marcas 
		{
			get
			{
				return this.GetAll<Marca>();
			}
		}
		
		public IQueryable<Cotizacionesdetalle> Cotizacionesdetalles 
		{
			get
			{
				return this.GetAll<Cotizacionesdetalle>();
			}
		}
		
		public IQueryable<Cotizacione> Cotizaciones 
		{
			get
			{
				return this.GetAll<Cotizacione>();
			}
		}
		
		public IQueryable<Costo> Costos 
		{
			get
			{
				return this.GetAll<Costo>();
			}
		}
		
		public IQueryable<Comprasdetalle> Comprasdetalles 
		{
			get
			{
				return this.GetAll<Comprasdetalle>();
			}
		}
		
		public IQueryable<Compra> Compras 
		{
			get
			{
				return this.GetAll<Compra>();
			}
		}
		
		public IQueryable<Clientestelefono> Clientestelefonos 
		{
			get
			{
				return this.GetAll<Clientestelefono>();
			}
		}
		
		public IQueryable<Clientesdireccione> Clientesdirecciones 
		{
			get
			{
				return this.GetAll<Clientesdireccione>();
			}
		}
		
		public IQueryable<Cliente> Clientes 
		{
			get
			{
				return this.GetAll<Cliente>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MySql";
			backend.ProviderName = "MySql.Data.MySqlClient";
		
			CustomizeBackendConfiguration(ref backend);
		
			return backend;
		}
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of InvEntitiesModel.
		/// </summary>
		/// <param name="config">The BackendConfiguration of InvEntitiesModel.</param>
		static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);
		
	}
	
	public interface IInvEntitiesModelUnitOfWork : IUnitOfWork
	{
		IQueryable<Ventasdetalle> Ventasdetalles
		{
			get;
		}
		IQueryable<Venta> Ventas
		{
			get;
		}
		IQueryable<Usuario> Usuarios
		{
			get;
		}
		IQueryable<Tipodocumento> Tipodocumentos
		{
			get;
		}
		IQueryable<Proveedoresdireccione> Proveedoresdirecciones
		{
			get;
		}
		IQueryable<Proveedorescontacto> Proveedorescontactos
		{
			get;
		}
		IQueryable<Proveedore> Proveedores
		{
			get;
		}
		IQueryable<Producto> Productos
		{
			get;
		}
		IQueryable<Marca> Marcas
		{
			get;
		}
		IQueryable<Cotizacionesdetalle> Cotizacionesdetalles
		{
			get;
		}
		IQueryable<Cotizacione> Cotizaciones
		{
			get;
		}
		IQueryable<Costo> Costos
		{
			get;
		}
		IQueryable<Comprasdetalle> Comprasdetalles
		{
			get;
		}
		IQueryable<Compra> Compras
		{
			get;
		}
		IQueryable<Clientestelefono> Clientestelefonos
		{
			get;
		}
		IQueryable<Clientesdireccione> Clientesdirecciones
		{
			get;
		}
		IQueryable<Cliente> Clientes
		{
			get;
		}
	}
}
#pragma warning restore 1591
