#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using InvDataAccess;

namespace InvDataAccess	
{
	public partial class Producto
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _producto1;
		public virtual string Producto1
		{
			get
			{
				return this._producto1;
			}
			set
			{
				this._producto1 = value;
			}
		}
		
		private int _marcas_Id;
		public virtual int Marcas_Id
		{
			get
			{
				return this._marcas_Id;
			}
			set
			{
				this._marcas_Id = value;
			}
		}
		
		private decimal _precio;
		public virtual decimal Precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				this._precio = value;
			}
		}
		
		private int _cantidad;
		public virtual int Cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				this._cantidad = value;
			}
		}
		
		private int _minimo;
		public virtual int Minimo
		{
			get
			{
				return this._minimo;
			}
			set
			{
				this._minimo = value;
			}
		}
		
		private Marca _marca;
		public virtual Marca Marca
		{
			get
			{
				return this._marca;
			}
			set
			{
				this._marca = value;
			}
		}
		
		private IList<Ventasdetalle> _ventasdetalles = new List<Ventasdetalle>();
		public virtual IList<Ventasdetalle> Ventasdetalles
		{
			get
			{
				return this._ventasdetalles;
			}
		}
		
		private IList<Cotizacionesdetalle> _cotizacionesdetalles = new List<Cotizacionesdetalle>();
		public virtual IList<Cotizacionesdetalle> Cotizacionesdetalles
		{
			get
			{
				return this._cotizacionesdetalles;
			}
		}
		
		private IList<Comprasdetalle> _comprasdetalles = new List<Comprasdetalle>();
		public virtual IList<Comprasdetalle> Comprasdetalles
		{
			get
			{
				return this._comprasdetalles;
			}
		}
		
	}
}
#pragma warning restore 1591
