#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using InvDataAccess;

namespace InvDataAccess	
{
	public partial class Proveedore
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _proveedor;
		public virtual string Proveedor
		{
			get
			{
				return this._proveedor;
			}
			set
			{
				this._proveedor = value;
			}
		}
		
		private string _nit;
		public virtual string Nit
		{
			get
			{
				return this._nit;
			}
			set
			{
				this._nit = value;
			}
		}
		
		private string _nrc;
		public virtual string Nrc
		{
			get
			{
				return this._nrc;
			}
			set
			{
				this._nrc = value;
			}
		}
		
		private IList<Proveedoresdireccione> _proveedoresdirecciones = new List<Proveedoresdireccione>();
		public virtual IList<Proveedoresdireccione> Proveedoresdirecciones
		{
			get
			{
				return this._proveedoresdirecciones;
			}
		}
		
		private IList<Proveedorescontacto> _proveedorescontactos = new List<Proveedorescontacto>();
		public virtual IList<Proveedorescontacto> Proveedorescontactos
		{
			get
			{
				return this._proveedorescontactos;
			}
		}
		
		private IList<Compra> _compras = new List<Compra>();
		public virtual IList<Compra> Compras
		{
			get
			{
				return this._compras;
			}
		}
		
	}
}
#pragma warning restore 1591
