#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using InvDataAccess;

namespace InvDataAccess	
{
	public partial class Venta
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private DateTime _fecha;
		public virtual DateTime Fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				this._fecha = value;
			}
		}
		
		private int _clientes_Id;
		public virtual int Clientes_Id
		{
			get
			{
				return this._clientes_Id;
			}
			set
			{
				this._clientes_Id = value;
			}
		}
		
		private int _tipoDocumentos_Id;
		public virtual int TipoDocumentos_Id
		{
			get
			{
				return this._tipoDocumentos_Id;
			}
			set
			{
				this._tipoDocumentos_Id = value;
			}
		}
		
		private string _nDoc;
		public virtual string NDoc
		{
			get
			{
				return this._nDoc;
			}
			set
			{
				this._nDoc = value;
			}
		}
		
		private int _pagado;
		public virtual int Pagado
		{
			get
			{
				return this._pagado;
			}
			set
			{
				this._pagado = value;
			}
		}
		
		private Cliente _cliente;
		public virtual Cliente Cliente
		{
			get
			{
				return this._cliente;
			}
			set
			{
				this._cliente = value;
			}
		}
		
		private Tipodocumento _tipodocumento;
		public virtual Tipodocumento Tipodocumento
		{
			get
			{
				return this._tipodocumento;
			}
			set
			{
				this._tipodocumento = value;
			}
		}
		
		private IList<Ventasdetalle> _ventasdetalles = new List<Ventasdetalle>();
		public virtual IList<Ventasdetalle> Ventasdetalles
		{
			get
			{
				return this._ventasdetalles;
			}
		}
		
	}
}
#pragma warning restore 1591
